import { NewsItem, TickerData, StockSentimentRow, LiveUpdate, MarketTrendItem, TelegramNotificationStatus } from './types';

export const mockNews: NewsItem[] = [
  // ── US ─────────────────────────────────────────────
  {
    id: '1',
    headline: 'Antitrust Updates: DOJ Closing Arguments Focus on Google\'s Default Search Deals',
    body: 'The landmark trial enters its final phase as regulators argue that payment to phone makers stifles competition...',
    sources: [
      { name: 'REUTERS', url: 'https://www.reuters.com/technology/google-antitrust-doj' },
    ],
    publishedAt: new Date(Date.now() - 4 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    impact: 'high',
    sentiment: 'bad',
    tickers: [
      { symbol: 'GOOGL', name: 'Alphabet Inc.', sentiment: 'down', sentimentScore: -7 },
    ],
    narrativeGroupId: 'ng-google-antitrust',
  },
  {
    id: '2',
    headline: 'Google Cloud Growth Accelerates as AI Demand Surges Among Enterprise Clients',
    body: 'Quarterly reports show a 28% increase in cloud revenue, driven by the rapid adoption of Vertex AI tools...',
    sources: [{ name: 'BLOOMBERG', url: 'https://www.bloomberg.com/news/google-cloud-ai' }],
    publishedAt: new Date(Date.now() - 4 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    impact: 'high',
    sentiment: 'good',
    tickers: [
      { symbol: 'GOOGL', name: 'Alphabet Inc.', sentiment: 'up', sentimentScore: 8 },
    ],
    narrativeGroupId: 'ng-google-cloud',
  },
  {
    id: '2b',
    headline: 'YouTube Advertising Revenue Beats Expectations Despite Creator Shift Trends',
    body: 'YouTube continues to dominate video advertising space with strong Q4 performance despite competition from short-form video platforms.',
    sources: [{ name: 'CNBC', url: 'https://www.cnbc.com/youtube-advertising-revenue' }],
    publishedAt: new Date(Date.now() - 12 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    impact: 'medium',
    sentiment: 'bad',
    tickers: [
      { symbol: 'GOOGL', name: 'Alphabet Inc.', sentiment: 'down', sentimentScore: -4 },
    ],
    narrativeGroupId: 'ng-google-ads',
  },
  {
    id: '2c',
    headline: 'Gemini 1.5 Pro Integration in Workspace Set to Redefine Productivity Suites',
    body: 'Google announces deep integration of Gemini 1.5 Pro across all Workspace applications, challenging Microsoft\'s Copilot dominance.',
    sources: [{ name: 'BLOOMBERG', url: 'https://www.bloomberg.com/news/gemini-workspace' }],
    publishedAt: new Date(Date.now() - 8 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    impact: 'medium',
    sentiment: 'good',
    tickers: [
      { symbol: 'GOOGL', name: 'Alphabet Inc.', sentiment: 'up', sentimentScore: 6 },
    ],
    narrativeGroupId: 'ng-google-ai',
  },
  {
    id: '3',
    headline: 'Nvidia Accelerates Data Center Dominance With New Blackwell Shipments',
    body: '$NVDA begins mass shipments of GB200 "Blackwell" GPUs to hyperscalers. $MSFT, $GOOGL, and $AMZN confirmed as top-tier customers, sending NVDA to fresh all-time highs.',
    sources: [
      { name: 'REUTERS', url: 'https://www.reuters.com/technology/nvidia-blackwell-shipments' },
      { name: 'CNBC', url: 'https://www.cnbc.com/nvidia-blackwell-gpu-shipments' },
    ],
    publishedAt: new Date(Date.now() - 12 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    impact: 'high',
    sentiment: 'good',
    tickers: [
      { symbol: 'NVDA', name: 'NVIDIA Corporation', sentiment: 'up', sentimentScore: 9 },
      { symbol: 'MSFT', name: 'Microsoft Corporation', sentiment: 'up', sentimentScore: 4 },
      { symbol: 'GOOGL', name: 'Alphabet Inc.', sentiment: 'up', sentimentScore: 3 },
      { symbol: 'AMZN', name: 'Amazon.com, Inc.', sentiment: 'up', sentimentScore: 3 },
    ],
    narrativeGroupId: 'ng-tech-earnings',
  },
  {
    id: '4',
    headline: 'Microsoft Cloud Revenue Misses Estimates on AI Capacity Constraints',
    body: '$MSFT Azure growth decelerates to 28% as GPU supply bottlenecks limit AI workload expansion. CFO warns capital expenditure will remain elevated through FY26.',
    sources: [{ name: 'CNBC', url: 'https://www.cnbc.com/microsoft-cloud-revenue-miss' }],
    publishedAt: new Date(Date.now() - 18 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    impact: 'medium',
    sentiment: 'bad',
    tickers: [
      { symbol: 'MSFT', name: 'Microsoft Corporation', sentiment: 'down', sentimentScore: -5 },
      { symbol: 'NVDA', name: 'NVIDIA Corporation', sentiment: 'up', sentimentScore: 3 },
    ],
    narrativeGroupId: 'ng-tech-earnings',
  },
  {
    id: '5',
    headline: 'Tesla Faces Recall Over FSD Software Anomaly in Cold Weather',
    body: 'NHTSA issues recall notice for 350,000 $TSLA vehicles due to Full Self-Driving software failures in temperatures below -10°C. Stock slides 3% in pre-market trading.',
    sources: [{ name: 'WSJ', url: 'https://www.wsj.com/autos/tesla-fsd-recall-cold-weather' }],
    publishedAt: new Date(Date.now() - 25 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    impact: 'high',
    sentiment: 'bad',
    tickers: [
      { symbol: 'TSLA', name: 'Tesla, Inc.', sentiment: 'down', sentimentScore: -8 },
    ],
  },
  {
    id: '6',
    headline: 'SEC Investigates Crypto Listing Practices at Major Exchanges',
    body: 'The SEC has opened investigations into several major exchanges regarding their token listing procedures, raising concerns about market manipulation and undisclosed conflicts of interest.',
    sources: [{ name: 'CNBC', url: 'https://www.cnbc.com/sec-crypto-listing-investigation' }],
    publishedAt: new Date(Date.now() - 35 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    impact: 'low',
    sentiment: 'bad',
    tickers: [
      { symbol: 'COIN', name: 'Coinbase Global', sentiment: 'down', sentimentScore: -4 },
      { symbol: 'MSTR', name: 'MicroStrategy Inc.', sentiment: 'down', sentimentScore: -3 },
    ],
  },

  // ── EU ─────────────────────────────────────────────
  {
    id: '7',
    headline: 'ECB Signals Pause in Rate Hikes Amid Slowing Euro Zone Growth',
    body: 'European Central Bank policymakers signal a potential pause in interest rate increases as economic data from Germany and France show contraction. $DAX futures rise on the news.',
    sources: [{ name: 'FT', url: 'https://www.ft.com/content/ecb-rate-pause-signal' }],
    publishedAt: new Date(Date.now() - 30 * 60 * 1000),
    regionTag: 'eu',
    countryCode: 'eu',
    impact: 'high',
    sentiment: 'good',
    tickers: [
      { symbol: 'EWG', name: 'iShares MSCI Germany', sentiment: 'up', sentimentScore: 5 },
      { symbol: 'FXE', name: 'Invesco CurrencyShares Euro', sentiment: 'up', sentimentScore: 4 },
    ],
  },
  {
    id: '8',
    headline: 'Amazon Acquires European Logistics Firm to Expand Delivery Network',
    body: '$AMZN acquires Dutch logistics giant PostNL in a €4.2B deal, strengthening last-mile delivery in 12 EU countries and threatening local rivals.',
    sources: [{ name: 'REUTERS', url: 'https://www.reuters.com/business/amazon-postnl-acquisition' }],
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    regionTag: 'eu',
    countryCode: 'eu',
    impact: 'medium',
    sentiment: 'good',
    tickers: [
      { symbol: 'AMZN', name: 'Amazon.com, Inc.', sentiment: 'up', sentimentScore: 6 },
    ],
  },

  // ── Asia ──────────────────────────────────────────
  {
    id: '9',
    headline: 'BOJ Maintains Ultra-Loose Monetary Policy, Yen Weakens',
    body: 'The Bank of Japan holds yield curve control unchanged, disappointing markets expecting a hawkish pivot. $USDJPY climbs above 150, raising intervention risk.',
    sources: [{ name: 'NIKKEI', url: 'https://asia.nikkei.com/boj-monetary-policy-unchanged' }],
    publishedAt: new Date(Date.now() - 45 * 60 * 1000),
    regionTag: 'asia',
    countryCode: 'jp',
    impact: 'high',
    sentiment: 'bad',
    tickers: [
      { symbol: 'FXY', name: 'Invesco CurrencyShares Yen', sentiment: 'down', sentimentScore: -6 },
      { symbol: 'EWJ', name: 'iShares MSCI Japan', sentiment: 'up', sentimentScore: 3 },
    ],
  },
  {
    id: '10',
    headline: 'China Stimulus Package Fails to Impress Markets',
    body: 'Beijing\'s latest round of fiscal stimulus falls short of analyst expectations. $FXI drops 2% in pre-market as property sector concerns persist.',
    sources: [{ name: 'CAIXIN', url: 'https://www.caixinglobal.com/china-stimulus-markets' }],
    publishedAt: new Date(Date.now() - 60 * 60 * 1000),
    regionTag: 'asia',
    countryCode: 'cn',
    impact: 'high',
    sentiment: 'bad',
    tickers: [
      { symbol: 'FXI', name: 'iShares China Large-Cap', sentiment: 'down', sentimentScore: -7 },
      { symbol: 'BABA', name: 'Alibaba Group', sentiment: 'down', sentimentScore: -5 },
      { symbol: 'PDD', name: 'PDD Holdings', sentiment: 'down', sentimentScore: -4 },
    ],
  },
  {
    id: '11',
    headline: 'SET Index Eyes 1,400 as Foreign Inflows Return to Thai Equities',
    body: 'Foreign investors return to Thai stocks after three months of outflows. Tourism recovery and baht stability bolster confidence in $GULF and $CPALL.',
    sources: [{ name: 'BANGKOKPOST', url: 'https://www.bangkokpost.com/business/set-1400-foreign-inflows' }],
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    regionTag: 'asia',
    countryCode: 'th',
    impact: 'medium',
    sentiment: 'good',
    tickers: [
      { symbol: 'GULF', name: 'Gulf Energy Development', sentiment: 'up', sentimentScore: 5 },
      { symbol: 'CPALL', name: 'CP ALL Public Company', sentiment: 'up', sentimentScore: 4 },
    ],
  },

  // ── Global ─────────────────────────────────────────
  {
    id: '12',
    headline: 'Apple Unveils Next-Gen Vision Pro With 40% Cost Reduction',
    body: '$AAPL announces Vision Pro 2 at $2,499 targeting mainstream adoption. Analysts upgrade price targets citing spatial computing growth runway.',
    sources: [{ name: 'BLOOMBERG', url: 'https://www.bloomberg.com/news/apple-vision-pro-2' }],
    publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    regionTag: 'global',
    countryCode: 'global',
    impact: 'medium',
    sentiment: 'good',
    tickers: [
      { symbol: 'AAPL', name: 'Apple Inc.', sentiment: 'up', sentimentScore: 7 },
    ],
  },
  {
    id: '13',
    headline: 'Google DeepMind Achieves Breakthrough in Protein Structure Prediction',
    body: '$GOOGL DeepMind\'s latest model predicts drug-protein interactions with 99.2% accuracy, potentially shortcutting years of pharmaceutical R&D pipeline.',
    sources: [{ name: 'NATURE', url: 'https://www.nature.com/articles/deepmind-protein-prediction' }],
    publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    regionTag: 'global',
    countryCode: 'global',
    impact: 'medium',
    sentiment: 'good',
    tickers: [
      { symbol: 'GOOGL', name: 'Alphabet Inc.', sentiment: 'up', sentimentScore: 6 },
    ],
  },
  {
    id: '14',
    headline: 'Oil Prices Surge as OPEC+ Announces Deeper Production Cuts',
    body: 'Brent crude jumps 4.2% after Saudi Arabia leads coalition in surprise 1.5M barrel/day reduction. Energy stocks $XOM $CVX rally while airlines $DAL $UAL face margin pressure.',
    sources: [
      { name: 'REUTERS', url: 'https://www.reuters.com/business/energy/opec-production-cuts' },
      { name: 'BLOOMBERG', url: 'https://www.bloomberg.com/news/opec-deeper-cuts' },
    ],
    publishedAt: new Date(Date.now() - 50 * 60 * 1000),
    regionTag: 'global',
    countryCode: 'global',
    impact: 'high',
    sentiment: 'neutral',
    tickers: [
      { symbol: 'XOM', name: 'Exxon Mobil Corporation', sentiment: 'up', sentimentScore: 6 },
      { symbol: 'CVX', name: 'Chevron Corporation', sentiment: 'up', sentimentScore: 5 },
    ],
  },
  {
    id: '15',
    headline: 'Global Semiconductor Shortage Eases as TSMC Ramps 3nm Production',
    body: 'TSMC reports 3nm yields above 80%, clearing backlog for $AAPL and $NVDA orders. Chip lead times fall to 12-week average, the lowest since 2021.',
    sources: [{ name: 'SEMI', url: 'https://www.semi.org/tsmc-3nm-production-ramp' }],
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    regionTag: 'global',
    countryCode: 'global',
    impact: 'low',
    sentiment: 'good',
    tickers: [
      { symbol: 'AAPL', name: 'Apple Inc.', sentiment: 'up', sentimentScore: 4 },
      { symbol: 'NVDA', name: 'NVIDIA Corporation', sentiment: 'up', sentimentScore: 5 },
    ],
  },
];

export const mockTickers: TickerData[] = [
  { symbol: 'NVDA', name: 'NVIDIA Corporation', price: 875.42, change: 24.13, changePercent: 2.84, trend: 'up', mentionCount: 18 },
  { symbol: 'AAPL', name: 'Apple Inc.', price: 182.31, change: -1.24, changePercent: -0.68, trend: 'down', mentionCount: 14 },
  { symbol: 'TSLA', name: 'Tesla, Inc.', price: 241.17, change: -7.83, changePercent: -3.15, trend: 'down', mentionCount: 11 },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', price: 162.45, change: 0.22, changePercent: 0.14, trend: 'flat', mentionCount: 9 },
  { symbol: 'AMZN', name: 'Amazon.com, Inc.', price: 198.73, change: -2.11, changePercent: -1.05, trend: 'down', mentionCount: 7 },
];

export const mockStockSentiment: StockSentimentRow[] = [
  { symbol: 'GOOG', impact: 'high', sentiment: 'down', sentimentLabel: 'Negative', mentionCount: 25, historical: { positive: 16, neutral: 4, negative: 5 }, score: 40 },
  { symbol: 'NVDA', impact: 'high', sentiment: 'up', sentimentLabel: 'Positive', mentionCount: 14, historical: { positive: 12, neutral: 4, negative: 2 }, score: 85 },
  { symbol: 'AAPL', impact: 'medium', sentiment: 'flat', sentimentLabel: 'Neutral', mentionCount: 17, historical: { positive: 12, neutral: 2, negative: 3 }, score: 57 },
  { symbol: 'MSFT', impact: 'low', sentiment: 'up', sentimentLabel: 'Positive', mentionCount: 18, historical: { positive: 12, neutral: 4, negative: 2 }, score: 75 },
  { symbol: 'TSLA', impact: 'high', sentiment: 'up', sentimentLabel: 'Positive', mentionCount: 20, historical: { positive: 4, neutral: 2, negative: 14 }, score: 81 },
  { symbol: 'AMZN', impact: 'low', sentiment: 'flat', sentimentLabel: 'Neutral', mentionCount: 31, historical: { positive: 4, neutral: 2, negative: 25 }, score: 42 },
  { symbol: 'MA', impact: 'high', sentiment: 'up', sentimentLabel: 'Positive', mentionCount: 14, historical: { positive: 12, neutral: 1, negative: 1 }, score: 90 },
  { symbol: 'AMD', impact: 'medium', sentiment: 'flat', sentimentLabel: 'Neutral', mentionCount: 7, historical: { positive: 1, neutral: 1, negative: 5 }, score: 45 },
  { symbol: 'SPY', impact: 'high', sentiment: 'down', sentimentLabel: 'Negative', mentionCount: 4, historical: { positive: 3, neutral: 0, negative: 1 }, score: 23 },
  { symbol: 'META', impact: 'high', sentiment: 'up', sentimentLabel: 'Positive', mentionCount: 34, historical: { positive: 24, neutral: 4, negative: 5 }, score: 69 },
];

export const liveUpdate: LiveUpdate = {
  headline: 'The Federal Reserve keeps interest rates unchanged at 3.50% – 3.75% following the latest FOMC meeting.',
  shortHeadline: 'Fed holds rates at 3.50%–3.75% after FOMC meeting.',
  publishedAt: new Date(Date.now() - 2 * 60 * 1000),
};

// Market Trends data (exact values from screenshot)
export const mockMarketTrends: MarketTrendItem[] = [
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    impactScore: 6,
    impactLevel: 'high',
    sentiment: 'good',
    mentionCount: 25,
    trend: 'up',
    sentimentHistorical: { positive: 16, negative: 5, neutral: 4 },
    score: 60,
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    impactScore: 9,
    impactLevel: 'high',
    sentiment: 'good',
    mentionCount: 14,
    trend: 'up',
    sentimentHistorical: { positive: 12, negative: 2, neutral: 4 },
    score: 85,
  },
  {
    symbol: 'AAPL',
    name: 'Apple Inc. \u2022 Nasdaq GS',
    impactScore: 7,
    impactLevel: 'medium',
    sentiment: 'good',
    mentionCount: 17,
    trend: 'up',
    sentimentHistorical: { positive: 12, negative: 3, neutral: 2 },
    score: 70,
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    impactScore: 7,
    impactLevel: 'low',
    sentiment: 'good',
    mentionCount: 18,
    trend: 'up',
    sentimentHistorical: { positive: 12, negative: 2, neutral: 4 },
    score: 75,
  },
  {
    symbol: 'TSLA',
    name: 'Tesla, Inc.',
    impactScore: -8,
    impactLevel: 'high',
    sentiment: 'bad',
    mentionCount: 20,
    trend: 'down',
    sentimentHistorical: { positive: 4, negative: 14, neutral: 2 },
    score: 20,
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com, Inc.',
    impactScore: 2,
    impactLevel: 'low',
    sentiment: 'neutral',
    mentionCount: 31,
    trend: 'flat',
    sentimentHistorical: { positive: 4, negative: 25, neutral: 2 },
    score: 42,
  },
  {
    symbol: 'MA',
    name: 'Mastercard Incorporated',
    impactScore: 9,
    impactLevel: 'high',
    sentiment: 'good',
    mentionCount: 14,
    trend: 'up',
    sentimentHistorical: { positive: 12, negative: 1, neutral: 1 },
    score: 90,
  },
  {
    symbol: 'AMD',
    name: 'Advanced Micro Devices',
    impactScore: 4,
    impactLevel: 'medium',
    sentiment: 'neutral',
    mentionCount: 7,
    trend: 'flat',
    sentimentHistorical: { positive: 1, negative: 5, neutral: 1 },
    score: 45,
  },
  {
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    impactScore: 2,
    impactLevel: 'high',
    sentiment: 'bad',
    mentionCount: 4,
    trend: 'down',
    sentimentHistorical: { positive: 3, negative: 1, neutral: 0 },
    score: 23,
  },
  {
    symbol: 'META',
    name: 'Meta Platforms, Inc.',
    impactScore: 7,
    impactLevel: 'high',
    sentiment: 'good',
    mentionCount: 34,
    trend: 'up',
    sentimentHistorical: { positive: 24, negative: 5, neutral: 4 },
    score: 69,
  },
  {
    symbol: 'ASML',
    name: 'ASML Holding N.V.',
    impactScore: 8,
    impactLevel: 'high',
    sentiment: 'good',
    mentionCount: 12,
    trend: 'up',
    sentimentHistorical: { positive: 10, negative: 1, neutral: 1 },
    score: 78,
  },
];

// Top 4 stocks for cards row (from screenshot)
export const topTrendingStocks: MarketTrendItem[] = [
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    impactScore: 9,
    impactLevel: 'high',
    sentiment: 'good',
    mentionCount: 14,
    trend: 'up',
    sentimentHistorical: { positive: 12, negative: 2, neutral: 4 },
    score: 85,
  },
  {
    symbol: 'AAPL',
    name: 'Apple Inc. \u2022 Nasdaq GS',
    impactScore: 7,
    impactLevel: 'medium',
    sentiment: 'good',
    mentionCount: 17,
    trend: 'up',
    sentimentHistorical: { positive: 12, negative: 3, neutral: 2 },
    score: 70,
  },
  {
    symbol: 'TSLA',
    name: 'Tesla, Inc.',
    impactScore: -8,
    impactLevel: 'high',
    sentiment: 'bad',
    mentionCount: 20,
    trend: 'down',
    sentimentHistorical: { positive: 4, negative: 14, neutral: 2 },
    score: 20,
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com, Inc.',
    impactScore: 2,
    impactLevel: 'low',
    sentiment: 'neutral',
    mentionCount: 31,
    trend: 'flat',
    sentimentHistorical: { positive: 4, negative: 25, neutral: 2 },
    score: 42,
  },
];

// Telegram notification status for watchlist
export const mockTelegramNotifications: TelegramNotificationStatus[] = [
  { symbol: 'NVDA', status: 'SENT', timestamp: new Date(Date.now() - 5 * 60 * 1000) },
  { symbol: 'TSLA', status: 'FAILED', timestamp: new Date(Date.now() - 5 * 60 * 1000) },
  { symbol: 'AAPL', status: 'SENT', timestamp: new Date(Date.now() - 75 * 60 * 1000) },
  { symbol: 'ASML', status: 'PROCESSING', timestamp: new Date(Date.now() - 75 * 60 * 1000) },
];
