import { NewsItem, TickerAnalysis, LiveUpdate, TelegramNotificationStatus, Category } from './types';

export const mockNews: NewsItem[] = [
  // ── US ─────────────────────────────────────────────
  {
    id: '1',
    headline: 'Antitrust Updates: DOJ Closing Arguments Focus on Google\'s Default Search Deals',
    body: 'The landmark trial enters its final phase as regulators argue that payment to phone makers stifles competition...',
    sources: [
      { name: 'REUTERS', url: 'https://www.reuters.com/technology/google-antitrust-doj' },
    ],
    publishedAt: new Date(Date.now() - 4 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'geopolitics',
    impact: 'high',
    sentiment: 'bad',
    tickers: [
      { symbol: 'GOOGL', name: 'Alphabet Inc.', sentiment: 'down', sentimentScore: -7 },
    ],
    narrativeGroupId: 'ng-google-antitrust',
  },
  {
    id: '2',
    headline: 'Google Cloud Growth Accelerates as AI Demand Surges Among Enterprise Clients',
    body: 'Quarterly reports show a 28% increase in cloud revenue, driven by the rapid adoption of Vertex AI tools...',
    sources: [{ name: 'BLOOMBERG', url: 'https://www.bloomberg.com/news/google-cloud-ai' }],
    publishedAt: new Date(Date.now() - 4 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'tech',
    impact: 'high',
    sentiment: 'good',
    tickers: [
      { symbol: 'GOOGL', name: 'Alphabet Inc.', sentiment: 'up', sentimentScore: 8 },
    ],
    narrativeGroupId: 'ng-google-cloud',
  },
  {
    id: '2b',
    headline: 'YouTube Advertising Revenue Beats Expectations Despite Creator Shift Trends',
    body: 'YouTube continues to dominate video advertising space with strong Q4 performance despite competition from short-form video platforms.',
    sources: [{ name: 'CNBC', url: 'https://www.cnbc.com/youtube-advertising-revenue' }],
    publishedAt: new Date(Date.now() - 12 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'tech',
    impact: 'medium',
    sentiment: 'bad',
    tickers: [
      { symbol: 'GOOGL', name: 'Alphabet Inc.', sentiment: 'down', sentimentScore: -4 },
    ],
    narrativeGroupId: 'ng-google-ads',
  },
  {
    id: '2c',
    headline: 'Gemini 1.5 Pro Integration in Workspace Set to Redefine Productivity Suites',
    body: 'Google announces deep integration of Gemini 1.5 Pro across all Workspace applications, challenging Microsoft\'s Copilot dominance.',
    sources: [{ name: 'BLOOMBERG', url: 'https://www.bloomberg.com/news/gemini-workspace' }],
    publishedAt: new Date(Date.now() - 8 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'tech',
    impact: 'medium',
    sentiment: 'good',
    tickers: [
      { symbol: 'GOOGL', name: 'Alphabet Inc.', sentiment: 'up', sentimentScore: 6 },
    ],
    narrativeGroupId: 'ng-google-ai',
  },
  {
    id: '3',
    headline: 'Nvidia Accelerates Data Center Dominance With New Blackwell Shipments',
    body: '$NVDA begins mass shipments of GB200 "Blackwell" GPUs to hyperscalers. $MSFT, $GOOGL, and $AMZN confirmed as top-tier customers, sending NVDA to fresh all-time highs.',
    sources: [
      { name: 'REUTERS', url: 'https://www.reuters.com/technology/nvidia-blackwell-shipments' },
      { name: 'CNBC', url: 'https://www.cnbc.com/nvidia-blackwell-gpu-shipments' },
    ],
    publishedAt: new Date(Date.now() - 12 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'tech',
    impact: 'high',
    sentiment: 'good',
    tickers: [
      { symbol: 'NVDA', name: 'NVIDIA Corporation', sentiment: 'up', sentimentScore: 9 },
      { symbol: 'MSFT', name: 'Microsoft Corporation', sentiment: 'up', sentimentScore: 4 },
      { symbol: 'GOOGL', name: 'Alphabet Inc.', sentiment: 'up', sentimentScore: 3 },
      { symbol: 'AMZN', name: 'Amazon.com, Inc.', sentiment: 'up', sentimentScore: 3 },
    ],
    narrativeGroupId: 'ng-tech-earnings',
  },
  {
    id: '4',
    headline: 'Microsoft Cloud Revenue Misses Estimates on AI Capacity Constraints',
    body: '$MSFT Azure growth decelerates to 28% as GPU supply bottlenecks limit AI workload expansion. CFO warns capital expenditure will remain elevated through FY26.',
    sources: [{ name: 'CNBC', url: 'https://www.cnbc.com/microsoft-cloud-revenue-miss' }],
    publishedAt: new Date(Date.now() - 18 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'tech',
    impact: 'medium',
    sentiment: 'bad',
    tickers: [
      { symbol: 'MSFT', name: 'Microsoft Corporation', sentiment: 'down', sentimentScore: -5 },
      { symbol: 'NVDA', name: 'NVIDIA Corporation', sentiment: 'up', sentimentScore: 3 },
    ],
    narrativeGroupId: 'ng-tech-earnings',
  },
  {
    id: '5',
    headline: 'Tesla Faces Recall Over FSD Software Anomaly in Cold Weather',
    body: 'NHTSA issues recall notice for 350,000 $TSLA vehicles due to Full Self-Driving software failures in temperatures below -10°C. Stock slides 3% in pre-market trading.',
    sources: [{ name: 'WSJ', url: 'https://www.wsj.com/autos/tesla-fsd-recall-cold-weather' }],
    publishedAt: new Date(Date.now() - 25 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'markets',
    impact: 'high',
    sentiment: 'bad',
    tickers: [
      { symbol: 'TSLA', name: 'Tesla, Inc.', sentiment: 'down', sentimentScore: -8 },
    ],
  },
  {
    id: '6',
    headline: 'SEC Investigates Crypto Listing Practices at Major Exchanges',
    body: 'The SEC has opened investigations into several major exchanges regarding their token listing procedures, raising concerns about market manipulation and undisclosed conflicts of interest.',
    sources: [{ name: 'CNBC', url: 'https://www.cnbc.com/sec-crypto-listing-investigation' }],
    publishedAt: new Date(Date.now() - 35 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'markets',
    impact: 'low',
    sentiment: 'bad',
    tickers: [
      { symbol: 'COIN', name: 'Coinbase Global', sentiment: 'down', sentimentScore: -4 },
      { symbol: 'MSTR', name: 'MicroStrategy Inc.', sentiment: 'down', sentimentScore: -3 },
    ],
  },

  // ── EU ─────────────────────────────────────────────
  {
    id: '7',
    headline: 'ECB Signals Pause in Rate Hikes Amid Slowing Euro Zone Growth',
    body: 'European Central Bank policymakers signal a potential pause in interest rate increases as economic data from Germany and France show contraction. $DAX futures rise on the news.',
    sources: [{ name: 'FT', url: 'https://www.ft.com/content/ecb-rate-pause-signal' }],
    publishedAt: new Date(Date.now() - 30 * 60 * 1000),
    regionTag: 'eu',
    countryCode: 'de',
    category: 'economy',
    impact: 'high',
    sentiment: 'good',
    tickers: [
      { symbol: 'EWG', name: 'iShares MSCI Germany', sentiment: 'up', sentimentScore: 5 },
      { symbol: 'FXE', name: 'Invesco CurrencyShares Euro', sentiment: 'up', sentimentScore: 4 },
    ],
  },
  {
    id: '8',
    headline: 'Amazon Acquires European Logistics Firm to Expand Delivery Network',
    body: '$AMZN acquires Dutch logistics giant PostNL in a €4.2B deal, strengthening last-mile delivery in 12 EU countries and threatening local rivals.',
    sources: [{ name: 'REUTERS', url: 'https://www.reuters.com/business/amazon-postnl-acquisition' }],
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    regionTag: 'eu',
    countryCode: 'nl',
    category: 'markets',
    impact: 'medium',
    sentiment: 'good',
    tickers: [
      { symbol: 'AMZN', name: 'Amazon.com, Inc.', sentiment: 'up', sentimentScore: 6 },
    ],
  },

  // ── Asia ──────────────────────────────────────────
  {
    id: '9',
    headline: 'BOJ Maintains Ultra-Loose Monetary Policy, Yen Weakens',
    body: 'The Bank of Japan holds yield curve control unchanged, disappointing markets expecting a hawkish pivot. $USDJPY climbs above 150, raising intervention risk.',
    sources: [{ name: 'NIKKEI', url: 'https://asia.nikkei.com/boj-monetary-policy-unchanged' }],
    publishedAt: new Date(Date.now() - 45 * 60 * 1000),
    regionTag: 'asia',
    countryCode: 'jp',
    category: 'economy',
    impact: 'high',
    sentiment: 'bad',
    tickers: [
      { symbol: 'FXY', name: 'Invesco CurrencyShares Yen', sentiment: 'down', sentimentScore: -6 },
      { symbol: 'EWJ', name: 'iShares MSCI Japan', sentiment: 'up', sentimentScore: 3 },
    ],
  },
  {
    id: '10',
    headline: 'China Stimulus Package Fails to Impress Markets',
    body: 'Beijing\'s latest round of fiscal stimulus falls short of analyst expectations. $FXI drops 2% in pre-market as property sector concerns persist.',
    sources: [{ name: 'CAIXIN', url: 'https://www.caixinglobal.com/china-stimulus-markets' }],
    publishedAt: new Date(Date.now() - 60 * 60 * 1000),
    regionTag: 'asia',
    countryCode: 'cn',
    category: 'economy',
    impact: 'high',
    sentiment: 'bad',
    tickers: [
      { symbol: 'FXI', name: 'iShares China Large-Cap', sentiment: 'down', sentimentScore: -7 },
      { symbol: 'BABA', name: 'Alibaba Group', sentiment: 'down', sentimentScore: -5 },
      { symbol: 'PDD', name: 'PDD Holdings', sentiment: 'down', sentimentScore: -4 },
    ],
  },
  {
    id: '11',
    headline: 'SET Index Eyes 1,400 as Foreign Inflows Return to Thai Equities',
    body: 'Foreign investors return to Thai stocks after three months of outflows. Tourism recovery and baht stability bolster confidence in $GULF and $CPALL.',
    sources: [{ name: 'BANGKOKPOST', url: 'https://www.bangkokpost.com/business/set-1400-foreign-inflows' }],
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    regionTag: 'asia',
    countryCode: 'th',
    category: 'markets',
    impact: 'medium',
    sentiment: 'good',
    tickers: [
      { symbol: 'GULF', name: 'Gulf Energy Development', sentiment: 'up', sentimentScore: 5 },
      { symbol: 'CPALL', name: 'CP ALL Public Company', sentiment: 'up', sentimentScore: 4 },
    ],
  },

  // ── EU ─────────────────────────────────────────────
  {
    id: '12',
    headline: 'Apple to Open Up NFC Payments in EU to Settle Antitrust Probe',
    body: '$AAPL bows to European Commission pressure, allowing third-party mobile wallets access to iPhone\'s tap-to-pay tech. Analysts view this as a major shift in iOS ecosystem control.',
    sources: [{ name: 'BLOOMBERG', url: 'https://www.bloomberg.com/news/apple-eu-nfc-payments' }],
    publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    regionTag: 'eu',
    countryCode: 'eu',
    category: 'tech',
    impact: 'medium',
    sentiment: 'good',
    tickers: [
      { symbol: 'AAPL', name: 'Apple Inc.', sentiment: 'up', sentimentScore: 7 },
    ],
  },
  {
    id: '13',
    headline: 'Google Reaches Preliminary Settlement in Multi-Billion EU Privacy Lawsuit',
    body: '$GOOGL agrees to revise targeted advertising practices in Europe under the Digital Markets Act, mitigating the risk of a record-breaking fine from Brussels regulators.',
    sources: [{ name: 'REUTERS', url: 'https://www.reuters.com/technology/google-eu-privacy-deal' }],
    publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    regionTag: 'eu',
    countryCode: 'eu',
    category: 'geopolitics',
    impact: 'medium',
    sentiment: 'good',
    tickers: [
      { symbol: 'GOOGL', name: 'Alphabet Inc.', sentiment: 'up', sentimentScore: 6 },
    ],
  },
  {
    id: '14',
    headline: 'European Natural Gas Prices Spike Amid Norwegian Facilities Outage',
    body: 'Benchmark Dutch gas futures jump 4% as unexpected maintenance at key North Sea infrastructure tightens European energy supply ahead of the winter season.',
    sources: [
      { name: 'REUTERS', url: 'https://www.reuters.com/business/energy/eu-gas-spike' },
      { name: 'BLOOMBERG', url: 'https://www.bloomberg.com/news/norway-gas-outage' },
    ],
    publishedAt: new Date(Date.now() - 50 * 60 * 1000),
    regionTag: 'eu',
    countryCode: 'eu',
    category: 'energy',
    impact: 'high',
    sentiment: 'neutral',
    tickers: [
      { symbol: 'XOM', name: 'Exxon Mobil Corporation', sentiment: 'up', sentimentScore: 6 },
      { symbol: 'CVX', name: 'Chevron Corporation', sentiment: 'up', sentimentScore: 5 },
    ],
  },
  {
    id: '15',
    headline: 'TSMC Secures €5 Billion EU Subsidy for First European Mega-Fab in Germany',
    body: 'Taiwan Semiconductor Manufacturing Co. officially breaks ground on its Dresden facility, a cornerstone of the European Chips Act aimed at securing local semiconductor supply.',
    sources: [{ name: 'FINANCIAL TIMES', url: 'https://www.ft.com/content/tsmc-eu-subsidy' }],
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    regionTag: 'eu',
    countryCode: 'eu',
    category: 'tech',
    impact: 'low',
    sentiment: 'good',
    tickers: [
      { symbol: 'AAPL', name: 'Apple Inc.', sentiment: 'up', sentimentScore: 4 },
      { symbol: 'NVDA', name: 'NVIDIA Corporation', sentiment: 'up', sentimentScore: 5 },
    ],
  },

  // ── Added: Coverage for all mockMarketTrends tickers ────
  {
    id: '16',
    headline: 'Meta\'s AI-Powered Ad Targeting Drives Record Q4 Revenue, Shares Jump 8%',
    body: '$META reports Q4 revenue of $42.3B, beating estimates by 5%. AI-driven ad optimization and Reels monetization fuel the surge. Reality Labs losses narrow to $3.7B as Quest 3 adoption accelerates.',
    sources: [{ name: 'BLOOMBERG', url: 'https://www.bloomberg.com/news/meta-q4-earnings-beat' }],
    publishedAt: new Date(Date.now() - 6 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'tech',
    impact: 'high',
    sentiment: 'good',
    tickers: [
      { symbol: 'META', name: 'Meta Platforms, Inc.', sentiment: 'up', sentimentScore: 8 },
    ],
  },
  {
    id: '17',
    headline: 'S&P 500 Drops 2.1% as Strong Jobs Data Crushes Rate Cut Expectations',
    body: 'Non-farm payrolls surge past forecasts, sending Treasury yields higher and $SPY to its worst daily loss in three weeks. Fed futures now price in only one cut this year, down from three.',
    sources: [{ name: 'WSJ', url: 'https://www.wsj.com/markets/sp500-drops-jobs-data' }],
    publishedAt: new Date(Date.now() - 15 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'markets',
    impact: 'high',
    sentiment: 'bad',
    tickers: [
      { symbol: 'SPY', name: 'SPDR S&P 500 ETF Trust', sentiment: 'down', sentimentScore: -6 },
    ],
  },
  {
    id: '18',
    headline: 'Mastercard Expands Open Banking Solutions Across Europe Following New ECB Directives',
    body: '$MA announces aggressive expansion of its open banking framework in 14 European countries, aligning with the latest European Central Bank mandates to boost digital transaction security.',
    sources: [{ name: 'REUTERS', url: 'https://www.reuters.com/business/finance/mastercard-eu-open-banking' }],
    publishedAt: new Date(Date.now() - 20 * 60 * 1000),
    regionTag: 'eu',
    countryCode: 'eu',
    category: 'markets',
    impact: 'high',
    sentiment: 'good',
    tickers: [
      { symbol: 'MA', name: 'Mastercard Incorporated', sentiment: 'up', sentimentScore: 8 },
    ],
  },
  {
    id: '19',
    headline: 'Amazon Loses $10B Pentagon Cloud Contract to Microsoft Azure',
    body: '$AMZN loses the JEDI II cloud computing contract to $MSFT Azure, marking a significant setback for AWS in the government sector. Amazon plans to protest the decision.',
    sources: [{ name: 'CNBC', url: 'https://www.cnbc.com/amazon-pentagon-cloud-contract-loss' }],
    publishedAt: new Date(Date.now() - 22 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'tech',
    impact: 'high',
    sentiment: 'bad',
    tickers: [
      { symbol: 'AMZN', name: 'Amazon.com, Inc.', sentiment: 'down', sentimentScore: -7 },
      { symbol: 'MSFT', name: 'Microsoft Corporation', sentiment: 'up', sentimentScore: 4 },
    ],
  },
  {
    id: '20',
    headline: 'AMD Data Center GPU Revenue Disappoints as Nvidia Maintains AI Training Dominance',
    body: '$AMD MI300X sales fall 15% short of guidance as hyperscalers consolidate AI training budgets around $NVDA Blackwell architecture. AMD pivots messaging toward inference-optimized workloads.',
    sources: [{ name: 'FT', url: 'https://www.ft.com/content/amd-data-center-disappoints' }],
    publishedAt: new Date(Date.now() - 32 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'tech',
    impact: 'medium',
    sentiment: 'bad',
    tickers: [
      { symbol: 'AMD', name: 'Advanced Micro Devices', sentiment: 'down', sentimentScore: -6 },
      { symbol: 'NVDA', name: 'NVIDIA Corporation', sentiment: 'up', sentimentScore: 3 },
    ],
  },
  {
    id: '21',
    headline: 'ASML Books Record €18B in EUV Orders as Chip Makers Race to Advanced Nodes',
    body: '$ASML reports its largest quarterly order book ever, driven by demand from TSMC, Samsung, and Intel for High-NA EUV lithography systems. Shares rise 5% in Amsterdam trading.',
    sources: [{ name: 'REUTERS', url: 'https://www.reuters.com/technology/asml-record-euv-orders' }],
    publishedAt: new Date(Date.now() - 40 * 60 * 1000),
    regionTag: 'eu',
    countryCode: 'nl',
    category: 'tech',
    impact: 'high',
    sentiment: 'good',
    tickers: [
      { symbol: 'ASML', name: 'ASML Holding N.V.', sentiment: 'up', sentimentScore: 8 },
    ],
  },
  {
    id: '22',
    headline: 'EU Fines Meta €1.2B Over Transatlantic Data Transfer Practices',
    body: 'The European Commission imposes a record privacy fine on $META for transferring EU user data to US servers without adequate safeguards. Meta says it will appeal the ruling.',
    sources: [{ name: 'FT', url: 'https://www.ft.com/content/meta-eu-data-fine' }],
    publishedAt: new Date(Date.now() - 55 * 60 * 1000),
    regionTag: 'eu',
    countryCode: 'ie',
    category: 'geopolitics',
    impact: 'medium',
    sentiment: 'bad',
    tickers: [
      { symbol: 'META', name: 'Meta Platforms, Inc.', sentiment: 'down', sentimentScore: -5 },
    ],
  },
  {
    id: '23',
    headline: 'FTC Expands Antitrust Lawsuit Against Amazon Over Marketplace Practices',
    body: 'Federal Trade Commission adds new allegations to its ongoing antitrust suit against $AMZN, claiming the company forces sellers to use its fulfillment services and penalizes those offering lower prices elsewhere.',
    sources: [{ name: 'WSJ', url: 'https://www.wsj.com/business/amazon-ftc-antitrust-expansion' }],
    publishedAt: new Date(Date.now() - 90 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'geopolitics',
    impact: 'high',
    sentiment: 'bad',
    tickers: [
      { symbol: 'AMZN', name: 'Amazon.com, Inc.', sentiment: 'down', sentimentScore: -8 },
    ],
  },

  // ── Crypto ────────────────────────────────────────────
  {
    id: 'crypto-1',
    headline: 'Bitcoin Surges Past $150K as Institutional Inflows Hit Record Levels',
    body: 'Bitcoin reaches a new all-time high driven by massive ETF inflows and growing adoption among sovereign wealth funds.',
    sources: [{ name: 'COINDESK', url: 'https://www.coindesk.com/bitcoin-150k' }],
    publishedAt: new Date(Date.now() - 15 * 60 * 1000),
    regionTag: 'global',
    countryCode: 'us',
    category: 'crypto',
    impact: 'high',
    sentiment: 'good',
    tickers: [
      { symbol: 'MSTR', name: 'MicroStrategy Inc.', sentiment: 'up', sentimentScore: 9 },
      { symbol: 'COIN', name: 'Coinbase Global', sentiment: 'up', sentimentScore: 7 },
    ],
  },
  {
    id: 'crypto-2',
    headline: 'EU Finalizes MiCA Enforcement: Stablecoin Issuers Face Strict Reserve Rules',
    body: 'The European Securities and Markets Authority publishes final guidelines for stablecoin reserves under the Markets in Crypto-Assets regulation.',
    sources: [{ name: 'REUTERS', url: 'https://www.reuters.com/eu-mica-stablecoins' }],
    publishedAt: new Date(Date.now() - 40 * 60 * 1000),
    regionTag: 'eu',
    countryCode: 'de',
    category: 'crypto',
    impact: 'medium',
    sentiment: 'bad',
    tickers: [
      { symbol: 'COIN', name: 'Coinbase Global', sentiment: 'down', sentimentScore: -4 },
    ],
  },

  // ── Healthcare ────────────────────────────────────────
  {
    id: 'health-1',
    headline: 'Novo Nordisk Obesity Drug Wins Expanded EU Approval for Cardiovascular Benefit',
    body: 'Wegovy receives expanded EU label allowing prescribing to reduce heart attack and stroke risk in overweight adults, opening a massive new market.',
    sources: [{ name: 'BLOOMBERG', url: 'https://www.bloomberg.com/novo-wegovy-eu' }],
    publishedAt: new Date(Date.now() - 20 * 60 * 1000),
    regionTag: 'eu',
    countryCode: 'dk',
    category: 'healthcare',
    impact: 'high',
    sentiment: 'good',
    tickers: [
      { symbol: 'NVO', name: 'Novo Nordisk A/S', sentiment: 'up', sentimentScore: 8 },
    ],
  },
  {
    id: 'health-2',
    headline: 'Pfizer Cuts 2026 Revenue Forecast Amid Declining COVID Vaccine Demand',
    body: 'Pfizer lowers its full-year guidance by $2B as global demand for COVID boosters continues to shrink faster than expected.',
    sources: [{ name: 'CNBC', url: 'https://www.cnbc.com/pfizer-revenue-cut' }],
    publishedAt: new Date(Date.now() - 55 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'healthcare',
    impact: 'medium',
    sentiment: 'bad',
    tickers: [
      { symbol: 'PFE', name: 'Pfizer Inc.', sentiment: 'down', sentimentScore: -6 },
    ],
  },

  // ── Commodities ───────────────────────────────────────
  {
    id: 'comm-1',
    headline: 'Gold Rallies to $2,800/oz as Central Banks Accelerate Reserve Diversification',
    body: 'Gold prices surge to record highs amid geopolitical uncertainty and continued de-dollarization by emerging market central banks.',
    sources: [{ name: 'FT', url: 'https://www.ft.com/gold-record-high' }],
    publishedAt: new Date(Date.now() - 25 * 60 * 1000),
    regionTag: 'global',
    countryCode: 'gb',
    category: 'commodities',
    impact: 'high',
    sentiment: 'good',
    tickers: [
      { symbol: 'GLD', name: 'SPDR Gold Shares', sentiment: 'up', sentimentScore: 7 },
      { symbol: 'NEM', name: 'Newmont Corp', sentiment: 'up', sentimentScore: 6 },
    ],
  },
  {
    id: 'comm-2',
    headline: 'Copper Prices Slide on Weaker China Manufacturing PMI Data',
    body: 'Industrial metals retreat as China factory activity contracts for the third consecutive month, signaling slowing demand.',
    sources: [{ name: 'REUTERS', url: 'https://www.reuters.com/copper-china-pmi' }],
    publishedAt: new Date(Date.now() - 70 * 60 * 1000),
    regionTag: 'asia',
    countryCode: 'cn',
    category: 'commodities',
    impact: 'medium',
    sentiment: 'bad',
    tickers: [
      { symbol: 'FCX', name: 'Freeport-McMoRan', sentiment: 'down', sentimentScore: -5 },
    ],
  },

  // ── Real Estate ───────────────────────────────────────
  {
    id: 're-1',
    headline: 'China Evergrande Liquidation Enters Final Phase as Court Approves Asset Sales',
    body: 'Hong Kong court approves the final tranche of asset disposals for the troubled property developer, marking the end of a years-long crisis.',
    sources: [{ name: 'SCMP', url: 'https://www.scmp.com/evergrande-liquidation' }],
    publishedAt: new Date(Date.now() - 35 * 60 * 1000),
    regionTag: 'asia',
    countryCode: 'cn',
    category: 'real-estate',
    impact: 'high',
    sentiment: 'bad',
    tickers: [],
  },
  {
    id: 're-2',
    headline: 'US Home Sales Jump 12% in February as Mortgage Rates Ease Below 6%',
    body: 'Existing home sales post the biggest monthly gain in two years as buyers return to the market amid falling borrowing costs.',
    sources: [{ name: 'NAR', url: 'https://www.nar.realtor/home-sales-feb' }],
    publishedAt: new Date(Date.now() - 80 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'real-estate',
    impact: 'medium',
    sentiment: 'good',
    tickers: [
      { symbol: 'XHB', name: 'SPDR Homebuilders ETF', sentiment: 'up', sentimentScore: 5 },
    ],
  },

  // ── Climate ───────────────────────────────────────────
  {
    id: 'climate-1',
    headline: 'EU Carbon Border Tax Takes Effect, Hitting Steel and Cement Imports',
    body: 'The Carbon Border Adjustment Mechanism (CBAM) begins charging importers for embedded carbon emissions, reshaping global trade flows.',
    sources: [{ name: 'FT', url: 'https://www.ft.com/eu-cbam-launch' }],
    publishedAt: new Date(Date.now() - 30 * 60 * 1000),
    regionTag: 'eu',
    countryCode: 'de',
    category: 'climate',
    impact: 'high',
    sentiment: 'neutral',
    tickers: [
      { symbol: 'MT', name: 'ArcelorMittal', sentiment: 'down', sentimentScore: -4 },
    ],
  },
  {
    id: 'climate-2',
    headline: 'Tesla Opens Largest Megapack Battery Factory in Shanghai',
    body: 'Tesla Energy ramps up production of grid-scale battery storage systems to meet surging demand from renewable energy projects across Asia.',
    sources: [{ name: 'BLOOMBERG', url: 'https://www.bloomberg.com/tesla-megapack-shanghai' }],
    publishedAt: new Date(Date.now() - 45 * 60 * 1000),
    regionTag: 'asia',
    countryCode: 'cn',
    category: 'climate',
    impact: 'medium',
    sentiment: 'good',
    tickers: [
      { symbol: 'TSLA', name: 'Tesla, Inc.', sentiment: 'up', sentimentScore: 6 },
    ],
  },

  // ── Defense ───────────────────────────────────────────
  {
    id: 'def-1',
    headline: 'NATO Members Agree to Raise Defense Spending Target to 3% of GDP',
    body: 'Alliance leaders reach historic agreement to increase the minimum defense spending threshold, benefiting major contractors.',
    sources: [{ name: 'REUTERS', url: 'https://www.reuters.com/nato-3pct-defense' }],
    publishedAt: new Date(Date.now() - 50 * 60 * 1000),
    regionTag: 'eu',
    countryCode: 'gb',
    category: 'defense',
    impact: 'high',
    sentiment: 'good',
    tickers: [
      { symbol: 'LMT', name: 'Lockheed Martin', sentiment: 'up', sentimentScore: 8 },
      { symbol: 'RTX', name: 'RTX Corporation', sentiment: 'up', sentimentScore: 7 },
    ],
  },
  {
    id: 'def-2',
    headline: 'South Korea Unveils $12B Defense Export Deal with Poland for K2 Tanks',
    body: 'Seoul and Warsaw finalize the largest arms export contract in Korean history, covering next-generation battle tanks and howitzers.',
    sources: [{ name: 'NIKKEI', url: 'https://asia.nikkei.com/korea-poland-k2-deal' }],
    publishedAt: new Date(Date.now() - 65 * 60 * 1000),
    regionTag: 'asia',
    countryCode: 'kr',
    category: 'defense',
    impact: 'medium',
    sentiment: 'good',
    tickers: [],
  },

  // ── Banking ───────────────────────────────────────────
  {
    id: 'bank-1',
    headline: 'JPMorgan Reports Record Q1 Profit Driven by Investment Banking Surge',
    body: 'JPMorgan Chase posts record quarterly earnings as deal-making and IPO underwriting activity rebounds strongly.',
    sources: [{ name: 'BLOOMBERG', url: 'https://www.bloomberg.com/jpm-q1-record' }],
    publishedAt: new Date(Date.now() - 10 * 60 * 1000),
    regionTag: 'us',
    countryCode: 'us',
    category: 'banking',
    impact: 'high',
    sentiment: 'good',
    tickers: [
      { symbol: 'JPM', name: 'JPMorgan Chase & Co.', sentiment: 'up', sentimentScore: 8 },
    ],
  },
  {
    id: 'bank-2',
    headline: 'Bank of Japan Signals End of Negative Rate Era, Yen Strengthens Sharply',
    body: 'BOJ Governor hints at normalizing monetary policy sooner than expected, sending the yen higher against major currencies.',
    sources: [{ name: 'NIKKEI', url: 'https://asia.nikkei.com/boj-rate-signal' }],
    publishedAt: new Date(Date.now() - 75 * 60 * 1000),
    regionTag: 'asia',
    countryCode: 'jp',
    category: 'banking',
    impact: 'high',
    sentiment: 'bad',
    tickers: [],
  },

];


export const liveUpdate: LiveUpdate = {
  headline: 'The Federal Reserve keeps interest rates unchanged at 3.50% – 3.75% following the latest FOMC meeting.',
  shortHeadline: 'Fed holds rates at 3.50%–3.75% after FOMC meeting.',
  publishedAt: new Date(Date.now() - 2 * 60 * 1000),
};

// Market Trends data (exact values from screenshot)
export const mockMarketTrends: TickerAnalysis[] = [
  // score = avg sentimentScore (-10..+10), positive = up, negative = down, 0 = neutral
  { symbol: 'GOOGL', name: 'Alphabet Inc.', impactLevel: 'high', sentiment: 'up', mentionCount: 25, sentimentHistorical: { positive: 16, neutral: 4, negative: 5 }, score: 2.0 },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', impactLevel: 'high', sentiment: 'up', mentionCount: 14, sentimentHistorical: { positive: 10, neutral: 2, negative: 2 }, score: 5.0 },
  { symbol: 'AAPL', name: 'Apple Inc. • Nasdaq GS', impactLevel: 'medium', sentiment: 'up', mentionCount: 17, sentimentHistorical: { positive: 12, neutral: 2, negative: 3 }, score: 5.5 },
  { symbol: 'MSFT', name: 'Microsoft Corporation', impactLevel: 'low', sentiment: 'up', mentionCount: 18, sentimentHistorical: { positive: 12, neutral: 4, negative: 2 }, score: 1.0 },
  { symbol: 'TSLA', name: 'Tesla, Inc.', impactLevel: 'high', sentiment: 'down', mentionCount: 20, sentimentHistorical: { positive: 4, neutral: 2, negative: 14 }, score: -8.0 },
  { symbol: 'AMZN', name: 'Amazon.com, Inc.', impactLevel: 'low', sentiment: 'down', mentionCount: 31, sentimentHistorical: { positive: 4, neutral: 2, negative: 25 }, score: -1.5 },
  { symbol: 'MA', name: 'Mastercard Incorporated', impactLevel: 'high', sentiment: 'up', mentionCount: 14, sentimentHistorical: { positive: 12, neutral: 1, negative: 1 }, score: 8.0 },
  { symbol: 'AMD', name: 'Advanced Micro Devices', impactLevel: 'medium', sentiment: 'down', mentionCount: 7, sentimentHistorical: { positive: 1, neutral: 1, negative: 5 }, score: -6.0 },
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF Trust', impactLevel: 'high', sentiment: 'down', mentionCount: 10, sentimentHistorical: { positive: 1, neutral: 2, negative: 7 }, score: -6.0 },
  { symbol: 'META', name: 'Meta Platforms, Inc.', impactLevel: 'high', sentiment: 'up', mentionCount: 34, sentimentHistorical: { positive: 24, neutral: 5, negative: 5 }, score: 1.5 },
  { symbol: 'ASML', name: 'ASML Holding N.V.', impactLevel: 'high', sentiment: 'up', mentionCount: 12, sentimentHistorical: { positive: 10, neutral: 1, negative: 1 }, score: 8.0 },
  // ── Regional & Sector tickers (referenced in mockNews) ──
  { symbol: 'COIN', name: 'Coinbase Global, Inc.', impactLevel: 'medium', sentiment: 'down', mentionCount: 8, sentimentHistorical: { positive: 2, neutral: 1, negative: 5 }, score: -4.0 },
  { symbol: 'MSTR', name: 'MicroStrategy Incorporated', impactLevel: 'low', sentiment: 'down', mentionCount: 5, sentimentHistorical: { positive: 1, neutral: 1, negative: 3 }, score: -3.0 },
  { symbol: 'BABA', name: 'Alibaba Group Holding Ltd.', impactLevel: 'high', sentiment: 'down', mentionCount: 11, sentimentHistorical: { positive: 2, neutral: 2, negative: 7 }, score: -5.0 },
  { symbol: 'PDD', name: 'PDD Holdings Inc.', impactLevel: 'medium', sentiment: 'down', mentionCount: 7, sentimentHistorical: { positive: 1, neutral: 1, negative: 5 }, score: -4.0 },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation', impactLevel: 'medium', sentiment: 'up', mentionCount: 8, sentimentHistorical: { positive: 5, neutral: 2, negative: 1 }, score: 6.0 },
  { symbol: 'CVX', name: 'Chevron Corporation', impactLevel: 'medium', sentiment: 'up', mentionCount: 6, sentimentHistorical: { positive: 4, neutral: 1, negative: 1 }, score: 5.0 },
  { symbol: 'FXI', name: 'iShares China Large-Cap ETF', impactLevel: 'high', sentiment: 'down', mentionCount: 9, sentimentHistorical: { positive: 1, neutral: 2, negative: 6 }, score: -7.0 },
  { symbol: 'EWG', name: 'iShares MSCI Germany ETF', impactLevel: 'medium', sentiment: 'up', mentionCount: 6, sentimentHistorical: { positive: 4, neutral: 1, negative: 1 }, score: 5.0 },
  { symbol: 'FXE', name: 'Invesco CurrencyShares Euro Trust', impactLevel: 'low', sentiment: 'up', mentionCount: 4, sentimentHistorical: { positive: 3, neutral: 1, negative: 0 }, score: 4.0 },
  { symbol: 'FXY', name: 'Invesco CurrencyShares Yen Trust', impactLevel: 'medium', sentiment: 'down', mentionCount: 6, sentimentHistorical: { positive: 1, neutral: 1, negative: 4 }, score: -6.0 },
  { symbol: 'EWJ', name: 'iShares MSCI Japan ETF', impactLevel: 'low', sentiment: 'up', mentionCount: 5, sentimentHistorical: { positive: 3, neutral: 1, negative: 1 }, score: 3.0 },
  { symbol: 'GULF', name: 'Gulf Energy Development PCL', impactLevel: 'low', sentiment: 'up', mentionCount: 4, sentimentHistorical: { positive: 3, neutral: 1, negative: 0 }, score: 5.0 },
  { symbol: 'CPALL', name: 'CP ALL Public Company Ltd.', impactLevel: 'low', sentiment: 'up', mentionCount: 5, sentimentHistorical: { positive: 3, neutral: 1, negative: 1 }, score: 4.0 }
];

// Stock Sentiment uses the same data as Market Trends (single source of truth)
export const mockStockSentiment: TickerAnalysis[] = mockMarketTrends;

// Telegram notification status for watchlist
export const mockTelegramNotifications: TelegramNotificationStatus[] = [
  { symbol: 'NVDA', status: 'SENT', timestamp: new Date(Date.now() - 5 * 60 * 1000) },
  { symbol: 'TSLA', status: 'FAILED', timestamp: new Date(Date.now() - 5 * 60 * 1000) },
  { symbol: 'AAPL', status: 'SENT', timestamp: new Date(Date.now() - 75 * 60 * 1000) },
  { symbol: 'ASML', status: 'PROCESSING', timestamp: new Date(Date.now() - 75 * 60 * 1000) },
];

// AI Intelligence Outlook per stock
export const mockAIOutlook: Record<string, string> = {
  NVDA: "NVIDIA's data center dominance continues to accelerate with Blackwell GPU shipments exceeding expectations. Hyperscaler demand remains robust with all major cloud providers expanding AI infrastructure. Supply constraints are the primary growth limiter, not demand — a strong position heading into FY26.",
  AAPL: "Apple's Vision Pro 2 announcement at a significantly reduced price point signals serious intent in spatial computing. TSMC's improving 3nm yields should help margin expansion. The stock remains range-bound as investors await clearer AI strategy articulation beyond on-device ML.",
  MSFT: "Azure growth deceleration to 28% reflects GPU supply constraints rather than demand weakness. Microsoft's Copilot ecosystem is gaining enterprise traction, but elevated capex through FY26 will pressure near-term margins. The long-term AI platform positioning remains best-in-class.",
  TSLA: "Tesla faces near-term headwinds from the NHTSA FSD recall affecting 350K vehicles. Cold weather software anomalies raise questions about autonomous driving timeline. However, manufacturing efficiency improvements and energy storage growth provide diversification beyond auto sales.",
  AMZN: "Amazon's European logistics expansion through the PostNL acquisition strengthens last-mile delivery across 12 EU countries. AWS remains the cloud market leader but faces intensifying competition from Azure and GCP. Retail margins continue their structural improvement trajectory.",
  MA: "Mastercard's cross-border transaction volumes remain exceptionally strong, benefiting from global travel recovery and digital payment adoption. The company's value-added services segment is growing above 20%, providing high-margin revenue diversification beyond core payment processing.",
  AMD: "AMD's data center GPU portfolio is gaining share against NVIDIA in inference workloads, though training remains dominated by competitors. The Xilinx integration is delivering cost synergies ahead of schedule. Client PC recovery provides cyclical tailwind.",
  SPY: "Broad market sentiment remains cautious as investors weigh strong earnings against elevated valuations and uncertainty around Federal Reserve policy. Sector rotation from growth to value suggests a maturing bull market cycle.",
  META: "Meta's ad revenue reacceleration driven by Reels monetization and AI-powered targeting improvements has exceeded expectations. Reality Labs losses remain elevated but the Quest 3 adoption curve is encouraging. Cost discipline under the 'Year of Efficiency' framework continues to drive margin expansion.",
  GOOGL: "Alphabet's aggressive integration of Gemini 1.5 Pro across Workspace and Search is yielding significant engagement gains. With Google Cloud reaching a $36B annual run rate, the company's AI monetization thesis is strengthening. However, ongoing DOJ antitrust proceedings create material regulatory risk that could reshape the search distribution model.",
  ASML: "ASML's record €18B EUV order book reflects the semiconductor industry's accelerating push toward advanced nodes. As the sole supplier of extreme ultraviolet lithography systems, ASML holds an unmatched monopoly position. High-NA EUV adoption by TSMC and Intel for 2nm processes should drive a multi-year revenue expansion cycle, though geopolitical export restrictions to China remain a key risk factor.",
  COIN: "Coinbase faces regulatory headwinds as the SEC intensifies scrutiny of crypto listing practices. Trading volumes remain depressed compared to 2021 peaks, but the company's institutional custody business and Base L2 chain provide diversification. Regulatory clarity remains the key catalyst.",
  MSTR: "MicroStrategy's Bitcoin-treasury strategy continues to polarize investors. The company's leveraged BTC exposure amplifies both upside and downside volatility. Enterprise software revenue provides minimal fundamental support at current valuations.",
  BABA: "Alibaba's restructuring into six business units is progressing but market confidence remains low amid China's property crisis and weak consumer spending. Cloud Intelligence Group's planned IPO could unlock value, though geopolitical tensions and regulatory uncertainty weigh on foreign investor sentiment.",
  PDD: "PDD Holdings' Temu platform is aggressively expanding in Western markets with ultra-low pricing, but mounting losses and regulatory scrutiny over product safety and labor practices pose risks. Domestic Pinduoduo business remains profitable with strong agricultural e-commerce growth.",
  XOM: "Exxon Mobil benefits from OPEC+ production cuts supporting crude prices above $80/barrel. The Pioneer Natural Resources acquisition strengthens Permian Basin positioning. Capital discipline and shareholder returns remain priorities, with buybacks running at $17.5B annually.",
  CVX: "Chevron's Hess acquisition adds Guyana assets providing long-duration production growth. Higher oil prices from OPEC+ cuts support near-term earnings, though downstream margins face seasonal pressure. The company maintains one of the strongest balance sheets among integrated oils.",
  FXI: "Chinese large-cap equities face persistent headwinds from property sector deleveraging, deflationary pressures, and disappointing fiscal stimulus. Foreign capital outflows continue as investors seek clarity on Beijing's economic policy direction. Valuations are historically cheap but lack a near-term catalyst.",
  EWG: "German equities benefit from ECB rate pause signals as the manufacturing-heavy DAX index is particularly sensitive to monetary policy shifts. However, structural challenges in the auto sector's EV transition and energy cost competitiveness remain medium-term headwinds.",
  FXE: "The euro finds support from ECB's relatively hawkish stance compared to other major central banks. However, diverging growth trajectories within the eurozone and political uncertainty in France and Germany limit upside potential against the dollar.",
  FXY: "The yen remains under pressure as the BOJ maintains ultra-loose monetary policy while other central banks hold rates higher. Intervention risk rises as USDJPY pushes above 150, but fundamental policy divergence continues to favor yen weakness.",
  EWJ: "Japanese equities benefit paradoxically from yen weakness, boosting exporters' earnings when repatriated. Corporate governance reforms under the Tokyo Stock Exchange's push for higher ROE are attracting foreign capital. The BOJ's eventual policy normalization remains the key risk event.",
  GULF: "Gulf Energy Development benefits from Thailand's tourism recovery and growing electricity demand. The company's renewable energy portfolio expansion aligns with government decarbonization targets. Foreign investor inflows to Thai equities provide additional tailwind.",
  CPALL: "CP ALL's convenience store network dominance in Thailand continues to drive steady same-store sales growth. The Lotus's integration is delivering synergies in supply chain and private label products. Rising tourist spending in urban locations provides cyclical upside.",
};

